### ISSUE TITLE
Prepending the attribute name to optionally be turned off on call of validate()

### ISSUE THREAD

**Issue by deporter** [ansman/validate.js#100]
I would like the ability to switch off the prepending of attribute names on call to validate.

**The API might look something like this:**
`validate(attributes, constraints, options)`

**Example:**
`validate({ propName1: 'example' }, { propName1: { presence: true } }, { prependAttributes: false })`

**Comment by ansman** [comment]
This can be done using the `fullMessages` option.

**Comment by deporter** [comment]
Oh wow, i totally missed that, thanks @ansman
