### ISSUE TITLE
Switch to JSON Schema as the schema declaration

### ISSUE THREAD

**Issue by michaelBenin** [ansman/validate.js#103]
https://github.com/json-schema/json-schema

Looks pretty similar. This project would get better traction if it was listed here under js validators:

http://json-schema.org/implementations.html

**Comment by ansman** [comment]
JSON Schema differs in that is not declarative but more descriptive.

Also, it's based around types and the validators are limited to each type. Not that that's wrong it's just a different approach and I do prefer the less verbose schema of validate.js

That's not saying that this can't change and in the future perhaps that is better way to go if the goal is true universal support. JSON Schema also has the benefit of supporting nested objects, though the syntax will be very verbose.

**Comment by michaelBenin** [comment]
I also prefer the less verbose schema of validate.js.

In my production applications I rarely pass around nested json.

**Comment by xhh2a** [comment]
I would NOT use validate.js if it used JSON Schema. JSON Schema is strait up horrible for ease of use (yes I had to use it before at my previous work place. It did not help productivity at all).

**Comment by ansman** [comment]
I'm closing this for now.
