### ISSUE TITLE
Feature Request: One of [Keys] Exists.

### ISSUE THREAD

**Issue by xhh2a** [ansman/validate.js#108]
It would be great if there was a validator that says one of the X following keys/objects must exist in the constraints rather than the current presence:true one. Essentially an OR logic.

Edit: untested implementation (will make a PR once I do test it)
```
var verify = require('validate.js');
var _ = require('lodash');

verify.validators.optional = function(value, options, key, attributes) {
  var other_keys = options.keys || [];
  if(value || !other_keys) {
    return undefined;
  } else {
    var has_value = _.chain(attributes).keys().intersection(other_keys).isEmpty().value();
    if (!has_value) {
      return options.message || "Is missing one of the required arguments from: " + String(other_keys);
    } else {
      return undefined;
    }
  }
}
```

**Comment by xhh2a** [comment]
I've realized my implementation won't work for validate.js as it uses lodash and this library is written to work in the frontend as well. I'm just going to start tracking my own additions implemented using lodash in a gist.

**Comment by airtonix** [comment]
You don't need lodash for this.

All must exist:
```es6
function check(attributes, options) {
  
  let keys = Object.keys(attributes),
    required = options.keys;

  return required.reduce( (result, item) => {
   return result &&  keys.includes(item);
  }, true);
}
```
http://www.es6fiddle.net/iro51z8e/

**Comment by xhh2a** [comment]
I think you misunderstand, I'm looking for an OR, not ALL (and).

It'd be something like this:
```
function check(attributes, options) {
  
  let keys = Object.keys(attributes),
    required = options.keys;

  return required.reduce( (result, item) => {
   return result ||  keys.includes(item);
  }, false);
}
```
