### ISSUE TITLE
Compare with other "field"

### ISSUE THREAD

**Issue by Matthijn** [ansman/validate.js#109]
Is it possible to compare with another field? There are two places where this could be useful:

Comparing "repeating password / email fields" or comparing dates (e.g one should be before another date). I'd say these are both fairly common in form handling. But I can't seem to figure out how to to either of these.

edit: It seems I can create a custom validator, and use an option to set the field to compare it to. And get that value from the attributes object.

**Comment by ansman** [comment]
You can validate that two fields are equal but that's it for now: http://validatejs.org/#validators-equality

If you want something more advanced you'd have to write your own validator.

**Comment by bayarja** [comment]
but when single value validation. it's not possible. right?

**Comment by ansman** [comment]
No, how would that even work?
