### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by sergeevabc** [ansman/validate.js#11]
Dear Nicklas,
could you be so kind and add at least a couple of pure JS/HTML demos?
So far there's no easy way to use Validate.js right out of the box.

**Comment by panique** [comment]
Same here! Project looks very good but it's hard to get into it as there's no *How to use it* example.

**Comment by panique** [comment]
Wow! THAT was fast! Thank you so much!

**Comment by ansman** [comment]
@panique Hehe, the issue has been opened since last year but your comment reminded me that it needed to be done so thank you :)
