### ISSUE TITLE
Use jQuery and Underscore / Lodash if they exist

### ISSUE THREAD

**Issue by hlfcoding** [ansman/validate.js#115]
Quite a bit of the codebase (`extend`, `contains`, `is*`, and `collectFormValue`) can be shortened by aliasing or incorporating their jQuery or Underscore or Lodash counterparts. This would reduce js parsing and load time.

Of course this would mean allowing the source to be built with 'batteries included' or not, the former option being great for simple script includes in the browser.

**Comment by ansman** [comment]
Perhaps when the library grows, for now the methods will remain.
