### ISSUE TITLE
Option to avoid prepending field name to error messages

### ISSUE THREAD

**Issue by jonahx** [ansman/validate.js#117]
Love this library.  I'd like one small but sometimes important option.  From the docs:

> Unless otherwise specified you can always specify the message option to customize the message returned if the validator doesn't pass. Just remember to not include the attribute name since it's automatically prepended to the error message.

There are a few issues with this:

1.  Sometimes you might not want to phrase your message with the field name as its subject.  That is, I might want "That's not a valid phone number" instead of "Phone number isn't valid".
2.  I may want a message where I don't mention the field name explicitly: "That doesn't look like something I can dial, my friend."
3.  I may want to use a different name than the field key, ie, "Telephone number isn't valid" when the key is "phoneNumber".

All could be solved with a simple option to avoid prepending the field name.

**Comment by ashah023** [comment]
+1

**Comment by ashah023** [comment]
Found this in the docs, for you:
> If you need an error not to be prefixed by the attribute add a leading ^ to the error and it won't be prepended. If you need to have a leading ^ but want the prefixing just write \^.

**Comment by ansman** [comment]
You can set this as default by doing this:
```
validate.options = {
  fullMessages: false
}
```
