### ISSUE TITLE
Examples are not working properly

### ISSUE THREAD

**Issue by raja-i4** [ansman/validate.js#120]
Hi,

I'm facing problem while running the given examples in node js environment.

this is how i'm using it.

```javascript
var validatorJS = 
	require('validator.js').Validator;
var validator = new validatorJS();

var constraints = {
		  creditCardNumber: {
		    presence: true,
		    format: {
		      pattern: /^(34|37|4|5[1-5]).*$/,
		      message: function(value, attribute, validatorOptions, attributes, globalOptions) {
		        return validator.validate.format("^%{num} is not a valid credit card number", {
		          num: value
		        });
		      }
		    },
		    length: function(value, attributes, attributeName, options, constraints) {
		      if (value) {
		        // Amex
		        if ((/^(34|37).*$/).test(value)) return {is: 15};
		        // Visa, Mastercard
		        if ((/^(4|5[1-5]).*$/).test(value)) return {is: 16};
		      }
		      // Unknown card, don't validate length
		      return false;
		    }
		  },
		  creditCardZip: function(value, attributes, attributeName, options, constraints) {
		    if (!(/^(34|37).*$/).test(attributes.creditCardNumber)) return null;
		    return {
		      presence: {message: "is required when using AMEX"},
		      length: {is: 5}
		    };
		  }
		};

validator.validate({creditCardNumber: "4"}, constraints);
```

While it is building constraints from the given config, it is failing by saying 'Should give a valid mapping object to Constraint'. It is failing while processing "presence" : true attribute.

Please find the screenshot below:

![image](https://cloud.githubusercontent.com/assets/17741219/14605858/36ff07e2-0598-11e6-92e4-18aa1b4636a8.png)

Please let me know how to resolve this problem.

**Comment by ansman** [comment]
You've included the library `validator.js`, this library name is called `validate.js`.

**Comment by raja-i4** [comment]
like presence, length, type, format, etc. 
for length: minimum, maximum, etc

I would like to see complete list of these. I mean complete schema definition.

**Comment by ansman** [comment]
These is no place where they are all shown together, but you have the list of all the constraints and if you click on a constraint you can read about all the options.

**Comment by raja-i4** [comment]
https://validatejs.org/#constraints   . this page has minimal list.

If i look at source code, i got the following:
presence, length, numericality, datetime, date, format, inclusion, exclusion, email, url, equality, pattern.

Pls let me know if i miss anything.

**Comment by ansman** [comment]
https://validatejs.org/#validators

**Comment by raja-i4** [comment]
ok, thanks. It has the same. :)

**Comment by raja-i4** [comment]
Hi,

I’m just reposting on the same as I couldn’t open a browser to create a new case.

My concern here is : I would like to find out excess data in “data” to be evaluated.
For instance,
 My constraints = {
“a” : { “presence”: true},
“b” : { “presence”: true},
“c” : { “presence”: true}
}

My data:

{
“a” : 1,
“b” : 2,
“c” : 3,
“d” : 4
}

My data has excess data “d”,  do you have logic inplace to determine such things with any options. (without any options, it is unable to find out excess data)

Here my concern mainly is strict validation: data must match the constraints. No more or no less data should be there.

Thanks,
Rajashekhar

**Comment by ansman** [comment]
No, there is currently no way to validate that.
But the [cleanAttributes](http://validatejs.org/#utilities-clean-attributes) function might help.

**Comment by raja-i4** [comment]
cleanAttributes should have named as retainAttributes, and cleanAttributes should remove the given attributes.

**Comment by raja-i4** [comment]
validate.extend(validate.validators.datetime, { // The value is guaranteed not to be null or undefined but otherwise it // could be anything. parse: function(value, options) { return +moment.utc(value); }, // Input is a unix timestamp format: function(value, options) { var format = options.dateOnly ? "YYYY-MM-DD" : "YYYY-MM-DD hh:mm:ss"; return moment.utc(value).format(format); } });


> validate({departure: "foobar"}, {departure: {datetime: true}});
ReferenceError: moment is not defined
    at Function.validate.extend.parse (repl:5:9)
    at Function.validate.validators.datetime.v.extend.parse (d:\workspace\nodejs\test\node_modules\validate.js\validate.js:881:20)
    at Function.v.extend.runValidations (d:\workspace\nodejs\test\node_modules\validate.js\validate.js:133:30)
    at validate (d:\workspace\nodejs\test\node_modules\validate.js\validate.js:25:21)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)

**Comment by ansman** [comment]
Please read the documentation: http://validatejs.org/#validators-datetime

**Comment by Walidkhan** [comment]
Hi ansman AOA  Plz Help Me what Was the Format Of TextArea To Show Blank Message In texrarea Field Plzz Upload here  Texara code Of Java Script?
