### ISSUE TITLE
Interested in separate domain name validator?

### ISSUE THREAD

**Issue by jjb** [ansman/validate.js#130]
It would be nice to pull out the domain name validation from the url validation and be able to use it by itself.

Would you be interested in such a feature? If so, I can take a stab at it.

**Comment by ansman** [comment]
Interesting, do you have a use case for this?

I'm leaning more towards improving the URL validator to allow what you want such as setting the schemes to an empty list, limiting the path to zero length etc.

**Comment by jjb** [comment]
> do you have a use case for this

i have a product which has in it a data type that is a domain name. the user can enter domain names to create a list of them. as they enter them we would like to validate them.

**Comment by ansman** [comment]
I think it's too specific actually, I'd have to say go with a custom validator for this.
