### ISSUE TITLE
Object level validation?

### ISSUE THREAD

**Issue by richard-reedy-volusion** [ansman/validate.js#131]
Is there a way to do an object level validation instead of field level?

For example, I would like my object to contain either

`{
  unlimited: true
}`
or
`{
  unlimited: false,
  usageLimit: 5
}`

and I would like to enforce that if unlimited is false usageLimit must be greater than 0 and if unlimited is true, I dont care about usageLimit.  Does this library support this?

**Comment by ansman** [comment]
You can do this with dynamic constraints:
```javascript
var constraints = {
  unlimited: {
    inclusion: [true, false],
    presence: true
  },
  usageLimit: function(value, attributes) {
    return attributes.unlimited ? null : {
      presence: true,
      numericality: {
        greaterThan: 0
      }
    };
  }
};

validate({unlimited: true}, constraints);
// undefined

validate({unlimited: false}, constraints);
// {usageLimit: ["Usage limit can't be blank"]}
```
