### ISSUE TITLE
Add validatorName to the list of error messages

### ISSUE THREAD

**Issue by mattruby** [ansman/validate.js#14]
It would be nice to be able to style error messages based on the validation type.  Perhaps the return type could be set as on option.  

Today:
{password: ["Password can't be blank"]}

Suggestion:
{password: [{validatorName:"length", errorMessage: "Password is too short (minimum is 6 characters)", value: "pass"}]}

The catalyst for wanting this change is a warning state where I suggest an email correction: "Did you mean comcast.net in place of comcast.com".  This message would be interactive with a link to the corrected address.

**Comment by ansman** [comment]
Released in 0.7.0
