### ISSUE TITLE
Checkbox group

### ISSUE THREAD

**Issue by mmiraglia** [ansman/validate.js#143]
Hi!
I've 3 checkboxes with the same name ( destiny[] ) and I need to verify that at least one is selected.
Any idea?
Thx!!!

**Comment by ansman** [comment]
Currently this isn't supported, but you can follow the progress in #1

**Comment by shojajou** [comment]
I have faced this issue before and made an effort which is followed and it works.

`validate.validators.checkboxList = (value, options, key, attributes) => {
    if (value.length === 0) return options.message;

    var validation = true;

    $.each(value, function (index, item) {
        if (item !== "") {
            validation = options.within.includes(item);
            if (validation === false)
                return;
        }
    });

    if (validation)
        return null;
    else
        return options.message;
}`

**Note #1:** You have to prepare your value in an array. _i.e._ If you have three different `checkbox`es which are holding `1`,`2` and `3` as value, your final value which should be passed to validation component should be something like this: `Array [1,3]`.

**Note #2:** My `checkboxList` component accepts an option in following schema:
`"validationKey": {
      checkboxList: {
                within: ["1", "2", "3"],
                message: "Your invalid warning message"
            }
}`

And FYI, I have written a piece of other codes to prepare my `checkboxList` component's food 😅.
`
function prepareCheckboxListValue(selector) {
    var chkbxs = $(selector);
    var value = [];

    $.each(chkbxs, function (index, item) {
        if ($(item).prop("checked"))
            value.push($(item).val());
    })

    return value;
}
`
