### ISSUE TITLE
Can't overwrite validate.validators.numericality.options.message

### ISSUE THREAD

**Issue by nitriques** [ansman/validate.js#145]
if I set a value to `validate.validators.numericality.options.message`, you can't customize the message when validating, using `message` or `notValid`. I would expect to still be able to provide custom messages  event if I set a default one. This problem looks specific to the numericality validator, as I do not have this problem with the 'presence' validator.

I've tried to set the message in both the constraints and option object, without any luck

This is using the `validate.single` function.

**Comment by nitriques** [comment]
Here's a fiddle with the P.O.C

https://jsfiddle.net/nitriques/4d9p3ju9/3/

As if you remove all other properties except message in the constraint, overwriting works. But if you add `onlyInteger` or `greaterThan`, it stops working.

**Comment by nitriques** [comment]
The fiddle is using the edge version

**Comment by ansman** [comment]
This is definitely a bug, nice catch.

**Comment by ansman** [comment]
Using the edge version you can now set `validate.validators.numericality.message` (note that you don't set the options, just the message)

**Comment by nitriques** [comment]
Hum my fiddle still does not works... I am missing something ?

**Comment by ansman** [comment]
Released in 0.11.0

**Comment by nitriques** [comment]
Thanks!
