### ISSUE TITLE
validating objects with nested array of objects

### ISSUE THREAD

**Issue by airtonix** [ansman/validate.js#146]
```es6
let data = {
  name: 'foo',
  items: [
    { name: 'bar', amount: 'e@ma.il', baz: true},
    { name: 'bok', amount: 60, baz: 'not a boolean'},
    { name: 'bog', amount: 60, baz: false},
  ]
}
```

1. Does validate.js handle writing a validation schema for this?
2. Does validate.js handle declaring errors as: `{ 'items.0.amount': [ 'must be a number'] }` ?

**Comment by ansman** [comment]
This is poorly supported at this moment, sorry.

You can track the progress in #1
