### ISSUE TITLE
optional fields

### ISSUE THREAD

**Issue by tamtakoe** [ansman/validate.js#15]
I can't describe optional field in validators. I need cancel other validators if `presence: false`.

Better. Rename `presence` to `required` and copy logic from angular.js: empty data always valid if `required` not `true`.

**Comment by shareef-sulopa** [comment]
I can see this piece of code from the library where it is checking if the value is empty or not.'

`isDefined: function(obj) {
      return obj !== null && obj !== undefined;
    }`
But this will not work for a value that is not null. 

I think this is going to fail for the below example. 

example var {someValue: ""}
isn't?

**Comment by bdjunayed** [comment]
Is it fixed yet, it looks like, I am facing the same issue.

```js
  // Constraints
  constraints = {
    name: {},
    email: {
      presence: false,
      email: true,
      length: {
        minimum: 5,
        maximum: 255
      }
    },
```
Output: "Email is not a valid email"

**Comment by bbusschots-mu** [comment]
@bdjunayed you need to update:

```
presence: false,
```

to:

```
presence: { allowEmpty: false },
```

The API changed a few versions ago.
