### ISSUE TITLE
import with webpack+npm

### ISSUE THREAD

**Issue by pablorsk** [ansman/validate.js#151]
I try to import library with import, but any module is defined. I try with:

``` javascript
var validate = require('validate.js');
let errors = validate ({ field_name: newValue } , { field_name: contract } );
```

but `require` don't work :(. I receive this error:

```
Cannot invoke an expression whose type lacks a call signature.
```

Any ideas for how can I import `validator.js` like this?

``` javascript
import * as ValidatorFunctions from 'validate.js';
import 'validate.js';
import { validator } from 'validate.js';
```

**Comment by ansman** [comment]
I have no idea I'm afraid, sorry.

**Comment by huan086** [comment]
```js
import validate from 'validate.js';
```

validate.js does UMD, which has `module.exports`. `import default from 'library'` will check if `library` is using `export` or `module.exports` when you use Babel to transpile from ES2015 to ES5, and `require` accordingly

**Comment by nebulousdog** [comment]
for anyone looking for Rollup solution, need to commonjs plugin.

`import commonjs from 'rollup-plugin-commonjs';` plus add `commonjs({ include: 'node_modules/**' }),` to your Rollup `plugins` config. then `import validate from 'validate.js';` will work.
