### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by tamtakoe** [ansman/validate.js#16]
Often I need to set custom `message` (or other fields) for all validators. Now I have to write every time:

```javascript
myField1: {
    email: {
        message: 'invalidEmail'
    }
}
...

myField2: {
    email: {
        message: 'invalidEmail'
    }
}
...
```

It is better:
```javascript
validators.defaults.email.message = 'invalidEmail';
...

myField1: {
    email: true
}
...

myField2: {
    email: true
}
```

**Comment by ansman** [comment]
Pushed an implementation of this in d06bd1346c4587def672d7685f92a3efc434c70d

Please have a look and see what you think, you can just close the issue if you're satisfied :)

**Comment by tamtakoe** [comment]
Good! But it only for error params, not for options (f.e. `dateOnly`). There is best practice if you make object with default options (f.e. `defaults`) and merge it with options.

Using [lodash defaults](https://lodash.com/docs#defaults):
```javascript
var defaults = {
    presence: ...
    ...
}
validators.defaults = defaults; //user can change it

...
//presence validator
_.defaults(options, defaults.presence);
```

**Comment by Jokero** [comment]
I think it should be possible to set default value of any validator option. So I agree with @tamtakoe :+1:

**Comment by ansman** [comment]
Sure, sounds like a resonable feature request.

**Comment by ansman** [comment]
Done, now you should be able to specify both default messages and default options. Please try it out and let me know what you think.

**Comment by Jokero** [comment]
Thanks! :+1: I tried to use default messages and it's working.
Added comment https://github.com/ansman/validate.js/commit/1b65319f05795e3bea3b82d70077c4c4d2e48d4c#commitcomment-9617489.
See please https://github.com/ansman/validate.js/issues/10#issuecomment-70854613 (it's about promises)

**Comment by tamtakoe** [comment]
It works! it may be rename `options` to more popular `defaults`
https://github.com/twbs/bootstrap/blob/master/js/popover.js#L24
http://docs.ractivejs.org/latest/ractive-defaults
http://stackoverflow.com/questions/8905507/jquery-plugin-defaults-and-options
But it is not critical.

Thank you for your work!
