### ISSUE TITLE
Numericality and international input

### ISSUE THREAD

**Issue by PhilipDavis** [ansman/validate.js#160]
numericality doesn't handle numbers where a comma is used as the decimal place separator.

I'm working on a project using validate.js v0.7.1. For what it's worth, I was able to hack in support by changing the two lines that say `value = +value` to `value = +(value || '').replace(/,/, '.')` -- this replaces the first comma it sees with a period.

**Comment by ansman** [comment]
Sadly validate.js cannot support all formats and languages. You probably don't send numbers with commas to server anyway.

**Comment by Legends** [comment]
> Sadly validate.js cannot support all formats and languages. You probably don't send numbers with commas to server anyway.

He????
