### ISSUE TITLE
Be able to ignore `select` elements

### ISSUE THREAD

**Issue by jayfresh** [ansman/validate.js#171]
I'm wondering if there's a reason why `collectFormValues` doesn't allow for `select` elements to be ignored with the `data-ignored` attribute like other form elements? The use case for me is that I'm including the same form on two different pages and I don't want it to be compulsory on all pages.

**Comment by ansman** [comment]
Nope, that's just a bug. Been fixed in master.

**Comment by ansman** [comment]
A fix has been released in 0.12.0
