### ISSUE TITLE
Problems with datetime validator: 86400000 is a number of miliseconds

### ISSUE THREAD

**Issue by nitriques** [ansman/validate.js#175]
On [this line](https://github.com/ansman/validate.js/blob/master/validate.js#L931) it says:

> 86400000 is the number of seconds in a day, 

This is not true: it's the number of milliseconds in a day. `60 * 60 * 24 = 86400`.

I would also add in the docs that the parse function must always return a number of ms (not a unix timestamp, which is in seconds) and the format function must always return a string.

Thanks!

**Comment by ansman** [comment]
Feel free to make a pull request!

**Comment by nitriques** [comment]
Fixed just after my fork. That's quick! Thanks ;)
