### ISSUE TITLE
one alphanumeric and lots of space are valid for length attribute

### ISSUE THREAD

**Issue by k-lusine** [ansman/validate.js#176]
Hi all, I'm facing such a problem and appreciate your help.

I'm using length attribute for validating user input length. Suppose I need minimum 50 characters. If user enters one alphanumeric and 49 spaces, the input is considered to be valid. How can I avoid that behavior?

Thanks in advance

**Comment by mcabs3** [comment]
@k-lusine why don't you trim your input before your validation?

**Comment by k-lusine** [comment]
@mcabs3 hmm thanks, I was thinking of smth more complex. For example a format attribute to specify which symbols shouldn't be considered when calculating the length. Anyway, thanks
