### ISSUE TITLE
Moment.js is there but still "Neither XDate or moment.js was found"

### ISSUE THREAD

**Issue by alvipeo** [ansman/validate.js#18]
I don't use in my AngularJS app neither AMD nor Require so I just include moment.js. And after the validate.js is included. Still, I get "Neither XDate or moment.js was found" error.

This is where the problem is - line 659 (v. 0.3.2):
        var moment = v.tryRequire("moment");

It returns null. But the global scope moment *is* defined.

**Comment by ansman** [comment]
I'll check it out as soon as I'm back from vacation

**Comment by alvipeo** [comment]
Same at the line 677:

var moment = v.tryRequire("moment");
