### ISSUE TITLE
Failed in Explorer

### ISSUE THREAD

**Issue by matrix-amiel** [ansman/validate.js#181]
Hi Nicklas.

Thanks you for great library!
I have problem with your library when it's run on IE.

It's failed in the line 563.
` for (j in input.options) {
            option = input.options[j];
            if (option.selected) {
              value.push(v.sanitizeFormValue(option.value, options));
            }
          }`   

IE doesn't support options property..
Could you fix it and write it in another way?

Thank you!
Amiel

**Comment by matrix-amiel** [comment]
This is great solution..

https://gist.github.com/brettz9/4212217

**Comment by ansman** [comment]
< IE 9 will not be supported.
