### ISSUE TITLE
Is it possible to disabled submit button if form has errors?

### ISSUE THREAD

**Issue by lavezzi1** [ansman/validate.js#186]
Hello everyone, 

The question is in title of this issue. Is it possible? If yes, can I see an example of how I can do it. Thanks a lot.

**Comment by brauliodiez** [comment]
Some UX experts consider that disabling "submit button" is a bad practice, the user gets confused, e.g. he doesn't know why he cannot click on the button.

If you want to achieve this I would hook to each OnChange event then there fire the validation, and there execute the global validation, and depending on the status enable / disable the submit button.

**Comment by ansman** [comment]
This is out of scope for this library.

@brauliodiez's solution should work just fine.
