### ISSUE TITLE
should not define the module name when doing amd wrapping

### ISSUE THREAD

**Issue by normanzb** [ansman/validate.js#20]
The module name should be left to AMD loader implementation to figure out, predefine the module name will cause inconsistency on actual path and virtual path. also confuse AMD loaders specially when "context" setting is enabled.

http://requirejs.org/docs/api.html#config-context

**Comment by ansman** [comment]
You are talking about this line, right?
```javascript
define("validate", [], function () { return validate; });
```

What would be the consequences of simply removing the first argument?

**Comment by normanzb** [comment]
yeah, I think we should remove the first argument so that:

1. If validate.js is running in non-amd environment, we use `global.validate`.
2. If it is running in AMD environment, the developers should knows where the module located and call `define` or `require` with corresponding path to load it.

**Comment by normanzb** [comment]
agreed on removing it?

**Comment by ansman** [comment]
Would there be any downsides of removing the name?

**Comment by ansman** [comment]
Released in 0.7.0, validate.js no longer supplies a name when calling `define`
