### ISSUE TITLE
Presence validator accepts empty string if `allowEmpty` is not set

### ISSUE THREAD

**Issue by GendelfLugansk** [ansman/validate.js#208]
I don't know if this is documentation issue or bug.

According to documentation, "If you don't want to reject empty objects, arrays or strings you can set the `allowEmpty` option to true", which implies that by default empty string will be rejected. In fact, presence validator accepts empty string until `allowEmpty` is specified and set to `false`.

It behaves this way because `! == false` is used to check this option and there is no default value for it (so it's undefined and `undefined !== false`):

```
if (options.allowEmpty !== false ? !v.isDefined(value) : v.isEmpty(value)) {
  return options.message || this.message || "can't be blank";
}
```

This behavior makes constraints bigger. It would be great if presence validator worked according to documentation.

**Comment by rkrdo** [comment]
This also happens to me with the version that's on `master`. 
```
#package.json

"validate.js": "git+ssh://git@github.com:ansman/validate.js.git"

# yarn.lock
+"validate.js@git+ssh://git@github.com:ansman/validate.js.git":
+  version "0.11.1"
+  resolved "git+ssh://git@github.com:ansman/validate.js.git#07f64ec81e8dd71d1553c20d750fbb3b7ed40018"
+
```

```
> const validate = require('validate.js')
undefined
> validate({ number: "" }, { number: { presence: true } })
undefined
> validate({ number: "" }, { number: { presence: {  allowEmpty: false } } })
{ number: [ 'Number can\'t be blank' ] }
```

With the version that's on `npm` (0.11.1), it doesn't

**Comment by ansman** [comment]
Fixed

**Comment by rzaharenkov** [comment]
You have updated the documentation but not the code 😄 I think it's weird to have `allowEmpty: true` by default at least for `presence` validator.

When I specify the attribute should be present I expect it to be defined and not to be empty.

**Comment by denyspopov** [comment]
This is extremely ludicrous to have a validation for, let me quote, "can't be blank" which allows blank values by default.

@ansman, if I may suggest to reopen this issue, consider the current behavior a bug and revert the changes done in 8b07b877882361c026ba01ae473ce4b417a6a345 and in the documentation.

**Comment by swrobel** [comment]
Since the default seems unlikely to be changed at this point:

```js
validate.validators.presence.options = { allowEmpty: false };
```
