### ISSUE TITLE
Option 'flatten' is wrongly documented or handled

### ISSUE THREAD

**Issue by fedulovivan** [ansman/validate.js#21]
On the site it is stated that passing option 'flatten' will make library return flat array instead of nested objects. But actually when this option is enabled an object with numeric keys is returned (which looks like an array but missing length property for example).
``` javascript
// got
{"0":"Message"}
// instead of expected
["Message"]
```

**Comment by ansman** [comment]
Ah, crap. This is due to the results being wrapped in a custom error class.

I'll look in to this.

**Comment by fedulovivan** [comment]
Thanks! When this fix will became a part of official release?

**Comment by ansman** [comment]
Not sure. Hopefully quite soon, only a few more things left.
