### ISSUE TITLE
Trim whitespace before validation

### ISSUE THREAD

**Issue by csergiu** [ansman/validate.js#210]
How could I trim the whitespace in an attribute constraint before performing validation? I have a credit card input that adds spaces on keypress and I want to remove the spaces before performing the regex pattern validation.

**Comment by Jokero** [comment]
Hi @csergiu. I created package which allows to filter, validate, set default values. It's very helpful for HTTP API for example. You can take a look https://github.com/Jokero/transformer-chain

**Comment by ansman** [comment]
This is out of scope for validate.js, you'd have to do that yourself.
