### ISSUE TITLE
Length constraints should be treated like other validation failures

### ISSUE THREAD

**Issue by caiges** [ansman/validate.js#213]
When a length constraint is declared and a value that does not have a length is provided, a number for instance, a regular error should be returned and that's it.
```js
constraints = {
  title: {
    length: {
      maximum: 50
    }
  }
};

validate({ title: 32 }, constraints); // Should return a regular error and not log to the console via console.error.
```
The error logged to the console "Attribute title has a non numeric value for `length`" should not be logged to the console. It's intrusive and inconsistent given that you can declare a numeric constraint, pass a string and not get the same console behavior -- "Title is not a number" is returned. Something like "Title does not have a valid length." would seem appropriate.

**Comment by ansman** [comment]
I agree, this was mostly focused on client side validation where you knew the type of your data but for server side validation it makes more sense to give a nicer error message.
