### ISSUE TITLE
Stop Validation on Failure

### ISSUE THREAD

**Issue by jpmelnik** [ansman/validate.js#214]
I have the following constraints:

```
const constraints = {
  key: {
    presence: {
      allowEmpty: false
    },
    numericality: {
        strict: true
    },
    length: {
      is: 11
    }
  }
};

```

When "presence" trigger an error I've got an array of errors:

```
[
"Key can't be blank",
"key must be a valid number",
"Key is the wrong length (should be 11 characters)"
]
```

I want to get the correct error or only one message for the correct wrong constraint.

Thanks

**Comment by 349989153** [comment]
why not always use the first item of error array?

**Comment by janudewangga** [comment]
@349989153 Wow, thanks, didn't see that
