### ISSUE TITLE
Invalid Pattern Matching with Regex

### ISSUE THREAD

**Issue by gottsohn** [ansman/validate.js#216]
Using the `format.pattern` validation in the schema/constraint sometimes returns wrong results for some regular expressions.
e.g
```
const constraint = {
  url: {
    presence: true,
    format: {
      pattern: /.\.+./,
      message: 'Error Bad url'
    }
  }
};


validate({url: 'gg.com'}, constraint);
// Should return null
// But it returns { url: ['Error Bad url']}
```

And running `/.\.+./.test('gg.com'); ` return `true`.

**Comment by chardskarth** [comment]
Hi @gottsohn,

According to the [documentation](https://validatejs.org/#validators-format), it states that the whole string should match instead of just a part if matching.

**Comment by gottsohn** [comment]
Hi @chardskarth, I don't understand what you mean.
Are u saying the matching is independent of the expression? That sucks.

A full or partial match should be determined by the expression, not the validator methods.

**Comment by ansman** [comment]
This is working as expected. The whole inputs needs to match. Simply add `.*` to the start and the end of your regexp.

**Comment by SirZach** [comment]
FWIW I'm stumbling on this issue just now and not supporting partial matching was pretty unexpected. It would be pretty easy to support it by swapping out
```
match = pattern.exec(value);
if (!match || match[0].length != value.length) {
  return message;
}
```
for
```
if (!pattern.test(value)) {
  return message;
}
```
and allow for more use-cases.

**Comment by gottsohn** [comment]
Been a while, but that sounds great.
