### ISSUE TITLE
datetime filter not working properly

### ISSUE THREAD

**Issue by yuvalk** [ansman/validate.js#22]
using
```
var result = validate(
      { data : "202015-01-19" },
      { data : { presence: true, datetime: { dateFormat: "YY-MM-DD" } }}
);
```
gives valid date..

* with moment.js

**Comment by ansman** [comment]
The documentation is a bit unclear.
The `dateFormat` flag is just used when printing date in an error message.

I'm not really happy with how the datetime validator works, it's very rudimentary and not flexible at all.

Until I've gotten a chance to overhaul it you can work around this by having your own parse function:
```javascript
validate.validators.datetime.parse = function(value, options) {
  // The third parameter enables strict parsing. Make sure you understand
  // the limitations of this: http://momentjs.com/docs/#parsing-two-digit-years
  var date = moment.utc(value, "YY-MM-DD", true);
  return date.isValid() ? +date : NaN;
}
```

**Comment by ansman** [comment]
I'm closing this since it isn't really a bug.

But I've opened up #23 and #24

**Comment by yuvalk** [comment]
[?]

Sincerely,
Yuval Kashtan

**Comment by ansman** [comment]
Please read my previous comment
