### ISSUE TITLE
Length validator doesn't type check.

### ISSUE THREAD

**Issue by abhirathmahipal** [ansman/validate.js#220]
The docs clearly state that the length validator checks the length of strings. Most validators check the type of the parameters before validating them but I have a feeling that you've forgotten to do so in the length validator.

I passed in an array which pass the length constraints and it passed the validation successfully despite being an array.

**Comment by ansman** [comment]
From the docs:
> Any object with the length property can be validated but all the default error messages refers to strings so make sure you override them if you plan on validating arrays using this.
