### ISSUE TITLE
Equality not work for validate single

### ISSUE THREAD

**Issue by vinhtq** [ansman/validate.js#222]
```
var errors = validate.single({ password: '123', confirmPassword: '123' }, { equality: "password" });

console.log(errors); // Print out error: ["is not equal to password" ]
```
Did I miss something?

**Comment by bbusschots-mu** [comment]
Equality doesn't make sense for single-value validation though - The `.single()` function checks if a single value matches a set of constraints - so, the value under  test is the entire first argument, and that is not equal to the password field.

Basically, equality makes no sense with `.single()`, you should use `.validate()`:

```
var errors = validate({ password: '123', confirmPassword: '123' }, { confirmPassword: { equality: "password" } });
console.log(errors); // undefined
```

**Comment by ansman** [comment]
What @bbusschots-mu said
