### ISSUE TITLE
Numericality validator fails on empty string

### ISSUE THREAD

**Issue by PavelPenkov** [ansman/validate.js#224]
```
var validate = require("validate.js")
var constraints = { amount: { numericality: true  } }
var form = { amount: '' }

console.log(validate(form, constraints)) // returns ["Amount is not a number"]
```

validate.js version 0.11.1
node version 6.11.2

**Comment by djheroez** [comment]
Having the same issue but it works on validate.js version 0.10.0

**Comment by alditis** [comment]
From [documentation](https://validatejs.org/):

> **numericality**
> The numericality validator will only allow numbers. Per default strings are coerced to numbers using the `+` operator. If this is not desirable you can set the **noStrings** option to `true` to disable this behaviour.
> 

What message did you expect?

**Comment by ansman** [comment]
Working as expected. Empty strings are considered values now.

**Comment by aepp** [comment]
```

var validate = require("validate.js")
var constraints = { amount: { numericality: true  } }
var form = { amount: '' }

console.log(validate(form, constraints)) // returns ["Amount is not a number"]
```

The behavior is still the same in v0.12.0. Any help?
