### ISSUE TITLE
Email validator documentation is inconsistent with behaviour

### ISSUE THREAD

**Issue by JamesM123** [ansman/validate.js#227]
The documentation for the email validator clearly states that 

> Important! Besides null and undefined being valid empty strings and whitespace only strings are also valid..

<img width="729" alt="screen shot 2017-09-14 at 15 10 11" src="https://user-images.githubusercontent.com/3850209/30416531-1d987264-995f-11e7-82a7-af1356a7681d.png">

However empty strings and whitespaces are not valid. The validator spec even has a test to that effect.
![screen shot 2017-09-14 at 15 11 49](https://user-images.githubusercontent.com/3850209/30416530-1d92c7ba-995f-11e7-8829-b657570f4f73.png)

Please make documentation consistent with expected behaviour.

**Comment by ansman** [comment]
Fixed
