### ISSUE TITLE
Email validator do not validate properly International Email

### ISSUE THREAD

**Issue by MaciejTrojniarz** [ansman/validate.js#228]
International Emails (https://en.wikipedia.org/wiki/International_email) cannot be properly validated by Email Validator. Code snippets for Spec that failing:
```
      expect(validate.single('用户@例子.广告', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('अजय@डाटा.भारत', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('юзер@екзампл.ком', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('θσερ@εχαμπλε.ψομ', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('Dörte@Sörensen.example.com', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('аджай@экзампл.рус', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
      expect(validate.single('żółć@wątroba.pl', {email: {message: 'Should be valid unicode email'}})).toBeUndefined()
```

**Comment by MaciejTrojniarz** [comment]
To fix that I had to have workaround from jqueryvalidation library.
so I'm using format with regex provided by them.
There is regex in jquery.validation. So instead of email validator I'm right now using: 
`
      format: {
        pattern: /^((([a-z]|\d|[!#$%&'*+\-/=?^_`{|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#$%&'*+\-/=?^_`{|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i
      },`

**Comment by ansman** [comment]
Email validation will never be perfect, Chrome doesn't not seem to like international emails either so I'm closing this.
