### ISSUE TITLE
Drop support for XDate

### ISSUE THREAD

**Issue by ansman** [ansman/validate.js#23]
Moment.js is the future

**Comment by yuvalk** [comment]
note that also the moment.js implementation should be changed, as they deprecated their empty constructor.

**Comment by ansman** [comment]
Well, it's not that easy really.

They've deprecated the fallback on the native `new Date()` parsing but there is no way to disable it besides specifying a format.

#24 will perhaps solve this anyway but I'm not sure yet

**Comment by alexkaraman85** [comment]
Nice!

**Comment by jadengore** [comment]
@ansman is this why I'm getting:

`Deprecation warning: moment construction falls back to js Date.`

**Comment by ansman** [comment]
@jadengore There is nothing validate.js can do to fix that, if you try to parse a date that isn't valid that error is always logged as it will try to parse it using the native `Date` constructor.

You could try doing this in your code if you just want to silence it:
```javascript
moment.createFromInputFallback = function(config) { return new Date(config.d); }
```

**Comment by jadengore** [comment]
@ansman Thank you for all your help, it did silence the error. Could be some of my unit tests putting bad data into date fields like you said. Very helpful, and it is limited to specifically the `validate.moment` and not my global moment.js dependency.

**Comment by ansman** [comment]
@jadengore I'm glad it helped, though the snipped I posted was invalid. I have updated it with a proper version.

Let me know if you have any other problems of if you come up with a better solution.
