### ISSUE TITLE
Incorrect documentation x2

### ISSUE THREAD

**Issue by willdady** [ansman/validate.js#231]
Under the [Writing your own validator](https://validatejs.org/#custom-validator) section.

> Make sure not to append the key name, this will be done automatically.

Should be:

> Make sure not to **prepend** the key name, this will be done automatically.

Under the [Presence validator](https://validatejs.org/#validators-presence).

> The presence validator validates that the value isn't defined.

Should be:

> The presence validator validates that the value **is** defined.

**Comment by ansman** [comment]
Fixed, thanks!
