### ISSUE TITLE
south african mobile number regex

### ISSUE THREAD

**Issue by freddiednml** [ansman/validate.js#235]
Hi guys,
Just an updated regex for en-ZA mobile numbers:
`'en-ZA': /^(\+?27|0)[6-8][0-9]{8}$/,`
Not sure if I should do a full pull request or how this generally works, but this regex accurately checks for mobile numbers including area(or in this case network) code instead of just length and country code.

**Comment by ansman** [comment]
validate.js does not have a phone number validator

**Comment by TheChuckster** [comment]
Is there a way we can make this a feature request?

**Comment by rdewolff** [comment]
With everyday day more mobile users, it would be a great addition to support mobile phone number in validate.js. What do you think?
