### ISSUE TITLE
Skip pattern based validations (i.e. URL) if empty string value?

### ISSUE THREAD

**Issue by george-norris-salesforce** [ansman/validate.js#237]
```
const rules = {
   url: {
     url: true
   }
};

const msg = validate(
  {url: ''},
  rules
);

console.log(msg);
"Url is not a valid url"
```
I don't require the user to fill out a URL.
URL field is undefined by default. 
But if they type into it, change mind and delete, it is empty string `'" "`.
And then above happens. 

I can do a check before calling `validate` and switch empty strings to null, but wondering if there is a better way to handle in the library.

**Comment by ansman** [comment]
Previously validate.js tried to be smart about it but failed. Now it will validate more strictly.
If you want to treat empty strings as `null` you'd have to convert it before validating.

If you are using [collectFormValues](http://validatejs.org/#utilities-collect-form-values) it should do this automatically for you.
