### ISSUE TITLE
Format/Pattern not working with numbers

### ISSUE THREAD

**Issue by george-norris-salesforce** [ansman/validate.js#239]
We are currently experiencing problems with working with number on inputs. 
We are using the `format` option to overcome issue when value contains an `e` 
[that issue is here](https://github.com/ansman/validate.js/issues/238)

The format is not working with number regex
Here is JSFiddle example:

[JSFiddle of the issue](https://jsfiddle.net/226myenw/)

```
const rules = {
   total_minutes: {
	   format: {
       pattern: /[0-9]+/,
       message: "can only contain 0-9"
     },
   }
};

const msg = validate(
  {total_minutes: 123},
  rules
);

console.log(msg);
//Total minutes can only contain 0-9
```

**Comment by ansman** [comment]
This is expected. The format validator only accepts strings.
