### ISSUE TITLE
Conditional Validation with Optional fields

### ISSUE THREAD

**Issue by BBlayne** [ansman/validate.js#245]
Suppose I have mandatory fields like FirstName, LastName, but then optional fields like SpouseFirstName, SpouseLastName.

I want to make it such that if someone enters text into SpouseLastName than obviously they must have text in SpouseFirstName.
```
		txtSpouseFirstName: {
			
			
		},
		txtSpouseLastName: function(value, attributes, attributeName) {
			if (value) {
				txtSpouseFirstName: {
					presence: {
						message: "^Cannot be blank"
					}
				}
			}
		}
```

I tried something like this, doesn't work.
```
		txtSpouseLastName: function(value, attributes, attributeName) {
			if (value) {
				if (!attributes.txtSpouseFirstName) {
					return {
						message: "^Test"
					}
				}
			}
		}
```

The above results in an unknown validator message.

I wrote a custom validator:
```
	validate.validators.spouse_conditional = function(value, options, key, attributes) {
		if (value) {
			if (attributes.txtSpouseFirstName 
			&& attributes.txtSpouseLastName
			&& attributes.txtSpouseDateOfBirth)
			{
				return null;
			}
			return "Please insure you also filled the other spouse fields";
		}
		
		return null;
	};
```
This does work, but results in the message only going in the messages field of the field I am currently writing in.

I think the ideal would be if I could have some fields have 'presence' but only optionally set.

Is there some way of getting the behavior I want?

edit: A minor issue with the custom validator solution is that if I enter in data in one field, which triggers the message, and then fill in the other fields, it doesn't refresh the validation for the earlier fields (but can still submit fine). 
```
			if (key == "txtSpouseFirstName") {		
				console.log(constraints);
				validate( {
					txtSpouseLastName: attributes.txtSpouseLastName 
				}, constraints);
				validate( {
					txtSpouseDateOfBirth: attributes.txtSpouseDateOfBirth 
				}, constraints);				
			}
```

Doesn't seem to work for solving this. Is there a way for one validator to trigger some other validator?

edit 2: Just triggering the onchange event to try to force it also doesn't work.
```
$("#txtSpouseLastName").change();
```

And weirdly document.getElementById('txtSpouseLastName').onchange(); results in an error 'is not a function'.

**Comment by ansman** [comment]
You can support dynamic validations by providing a function instead of validators:
```javascript
  creditCardZip: function(value, attributes, attributeName, options, constraints) {
    if (!(/^(34|37).*$/).test(attributes.creditCardNumber)) return null;
    return {
      presence: {message: "is required when using AMEX"},
      length: {is: 5}
    };
  }
```

**Comment by BBlayne** [comment]
I am using functions as you can see in my provided snippets to get close to the intended functionality, but it isn't working as intended.

Example: I fill in SpouseFirstName, it now says "Please fill in the remaining spouse fields" great. I fill in SpouseLastName, it too displays the message, also great.

I then fill in SpouseDateOfBirth, it doesn't display any errors, great! But wait! The error messages for the first two fields still appear!

I need a means of refreshing these fields so it get rids of the message.
