### ISSUE TITLE
email validator with empty string slow?

### ISSUE THREAD

**Issue by okeydoke** [ansman/validate.js#25]
Hey, I've been writing some unit tests for my node.js project and one of the tests is showing as slow quite often, 40-100ms. Basically its validating an empty string against an email. eg:
```javascript
validate({email:""},  {
  email: {
    presence: true,
    email: true,
    length: {
      minimum: 6,
      maximum: 255
    }
  }
});
```

Running in the browser it seems to be about 15-20ms which isn't as bad but still seems pretty slow?

**Comment by ansman** [comment]
Test code
---
```javascript
// This line is node specific
var validate = require("validate.js");
console.time("validate");
validate({email:""},  {
  email: {
    presence: true,
    email: true,
    length: {
      minimum: 6,
      maximum: 255
    }
  }
});
console.timeEnd("validate");
```

Results
---
```
           | Chrome  | Node.js |
-----------+---------+---------+
    Run #1 | 7.328ms |     2ms |
    Run #2 | 0.246ms |     0ms |
    Run #3 | 0.094ms |     0ms |
    Run #4 | 0.085ms |     0ms |
    Run #5 | 0.109ms |     0ms |
    Run #6 | 0.103ms |     1ms |
    Run #7 | 0.242ms |     0ms |
    Run #8 | 0.125ms |     0ms |
    Run #9 | 0.159ms |     0ms |
   Run #10 | 0.159ms |     0ms |
-----------+---------+---------+
      Mean | 0.865ms |     0ms |
 Std. dev. | 2.272ms |     1ms |
```

Conclusion
---
Measuring performance is tricky.
Chrome has lots of JIT compilation which speeds up subsequent calls.
Node seems to be consistently fast.

How did you perform your tests?

**Comment by okeydoke** [comment]
Sorry didn't get round to this before but heres a jsperf test http://jsperf.com/js-validate-empty-string

Noticeably slower across the 3 browsers I tested. I would of though the performance would be comparable to null/undefined

**Comment by ansman** [comment]
This particular problem was fixed in d9944f48595b1f74d0edb844bb8035dd0cd8c20b but the problem probably comes from the RegExp that parses the email.

It is bound to be pretty slow. Is this causing any actual problems?

**Comment by okeydoke** [comment]
Yeah I guess its not a huge deal, but eking out a little more performance would be nice. But just had a quick look at the source and it doesn't look as easy as something like `email === "" return false` though

**Comment by ansman** [comment]
If you rerun the test against the 0.4.0 source it should be faster for empty strings
