### ISSUE TITLE
How to validate only if any value is entered (i.e. validation on optional fields)?

### ISSUE THREAD

**Issue by activebiz** [ansman/validate.js#259]
Hi,

I have tried searching for an answer to my following query without luck.
I want to validate a field only if a value is entered. So its allow to be empty/null/undefined but if any value is entered then I need to make sure the min. length is 3.

I have tried,
```
telephone1: {
        presence: false,
        length: { minimum: 3 }
}

```

```
telephone1: {
        presence: {allowEmpty: true},
        length: { minimum: 3 }
}
```

But can not make it work.

any idea?

**Comment by activebiz** [comment]
I ended up writing custom validator as follows (typescript):

`validate.validators.minLengthWithAllowEmpty = (value: string, minlength: number) => {
    if (!value) {
        return;
    }
    if (value.length < minlength) {
        return `must be at least ${minlength} characters`;
    }
    return;
};`

hope this helps someone.

**Comment by Scit** [comment]
> I ended up writing custom validator as follows:
> 
> ```
> validate.validators.minLengthWithAllowEmpty = (value: string, minlength: number) => {
>     if (!value) {
>         return;
>     }
>     if (value.length < minlength) {
>         return `must be at least ${minlength} characters`;
>     }
>     return;
> };
> ```
> hope this helps someone.

Are you gonna writing a custom validator for any case? It's not flexible. It's not a solution at all.
