### ISSUE TITLE
Remove field name from error message

### ISSUE THREAD

**Issue by droganov** [ansman/validate.js#28]
It' doesn't make sense when you output error in some other than english language.

**Comment by ansman** [comment]
Well, you can set a different default message with the changes in 0.4.0




But I see your point. Perhaps I could add a way to map attribute names to message names.

**Comment by droganov** [comment]
When I set custom message, I get: fieldName укажите адрес электронной почты
It's not natural.

**Comment by ansman** [comment]
How are you setting the custom message?

**Comment by Jokero** [comment]
Set fullMessages as false in options

**Comment by droganov** [comment]
validate.validators.presence.message = "message"
will check fullMessages, thank you!
