### ISSUE TITLE
Is there a way to validate with dependancies?

### ISSUE THREAD

**Issue by deep-link** [ansman/validate.js#296]
Is there a way to define validate attribute dynamicaly? as a example

`
age : required,
`
`guardianName: if age < 18 then required else notRequied`

**Comment by jakerobers** [comment]
I would have two separate validators. One for dependents and one for guardians. Then you can split your data set by these two categories and validate separately.

**Comment by ansman** [comment]
Yes there is, here is an example from the documentation:
```js
  creditCardZip: function(value, attributes, attributeName, options, constraints) {
    if (!(/^(34|37).*$/).test(attributes.creditCardNumber)) return null;
    return {
      presence: {message: "is required when using AMEX"},
      length: {is: 5}
    };
  }
```
