### ISSUE TITLE
Scroll to first error

### ISSUE THREAD

**Issue by adelacreative** [ansman/validate.js#327]
How can we scroll to the first error the form finds? If the form is big and error is at top, it's not visible.

**Comment by tcdurks** [comment]
i'm using this inside `handleFormSubmit()` 

        if(errors){
          $('html, body').animate({
            scrollTop: $('.your-error-class').offset().top -100
          }, 1000);
        }

**Comment by adelacreative** [comment]
Thank you very much, this is exactly what I needed!
