### ISSUE TITLE
Conditional Validation

### ISSUE THREAD

**Issue by mgodwin** [ansman/validate.js#33]
Any plans to support conditional validation paths, like rails' `if:` or `unless:` directives?

**Comment by ansman** [comment]
You can already do this, sort of.

A constraint can be a function which is called to retrieve constraint like so:
```javascript
var constraints = {
  creditCardNumber: {
    presence: true,
    format: {
      pattern: /^(34|37|4|5[1-5]).*$/,
      message: "must be a valid Amex, Visa or Mastercard number"
    },
    length: function(value, attributes, attributeName) {
      if (value) {
        // Amex
        if ((/^(34|37).*$/).test(value)) return {is: 15};
        // Visa, Mastercard
        if ((/^(4|5[1-5]).*$/).test(value)) return {is: 16};
      }
      // Unknown card, don't validate length
      return false;
    }
  },
  creditCardZip: function(value, attributes, attributeName) {
    if (!(/^(34|37).*$/).test(attributes.creditCardNumber)) return null;
    return {
      presence: true,
      length: {is: 5}
    };
  }
};

validate({creditCardNumber: "4"}, constraints);
// => {"creditCardNumber": ["Credit card number is the wrong length (should be 16 characters)"]}

validate({creditCardNumber: "4242424242424242"}, constraints);
// => undefined

validate({creditCardNumber: "340000000000000"}, constraints);
// => {"creditCardZip": ["Credit card zip can't be blank"]}
```

**Comment by mgodwin** [comment]
Interesting.  I personally am a fan of how the validation in rails reads, also how it would bring clarity to what is happening in your particular example:

```js
var constraints = {
  creditCardNumber: {
    presence: true,
    format: {
      pattern: /^(34|37|4|5[1-5]).*$/,
      message: "must be a valid Amex, Visa or Mastercard number"
    },
    length: {
      is: 15,
      if: function(obj) { return (/^(34|37).*$/).test(obj.creditCardNumber) }
    },
    length: {
      is: 16,
      if: function(obj) { return (/^(4|5[1-5]).*$/).test(obj.creditCardNumber) }
    }
  }
}
```

fwiw, I like that there's an interim solution as you outlined, but what do you think about doing something along those lines?  (I realize that it may not be possible to specify the same validator more than once, so that may be a limitation that I'm not aware of.)  I also like that you could even reference a more well-named function like:

```js
var isAmexNumber = function(obj) { ... }
//...
length: { 
  is: 16,
  if: isAmexNumber 
}
```

Thoughts?

Another thought I had is possibly binding the object being validated to `this` for the callback function so you wouldn't even have to pass it - but not sure how that would impact other areas of the validation.

**Comment by ansman** [comment]
As you mentioned you cannot have the same validator more than once.

The original though of this library was to be able to share validators between a server and the client so everything that prevents that has pretty low priority.

So to answer your original question no, I don't have current plans to add these conditional directives unless these is a major need for it.

**Comment by alexkaraman85** [comment]
Im with @ansman, have the capability of passing a callback function with ```value, attributes, attributeName``` parameters is very flexiable and solves @mgodwin request.  Callback as presented on validate.js is an extremely robust solution that solves the necessity for additional API like ```:if``` and ```:then```.  

This is not an issue of validate.js.

**Comment by ansman** [comment]
I'm closing this as this is not likely to be implemented any time soon.
