### ISSUE TITLE
Validatejs found Bug

### ISSUE THREAD

**Issue by vinothwindows47** [ansman/validate.js#34]
When using validatejs , if the validate ( value or constraints ) contains ". " character which will not validate properly.For Example ,

values = {
                       basic.commandName: "",
                       basic.name: "",
                       workingDirectory: "cide"
              };

constraints = {
                           basic.commandName: Object,
                           basic.name: Object,
                           workingDirectory: Object
                     };

To fix this one ,

Please remove check in your code in lune number between 282 .

            case '.':
            if (escape) {
              escape = false;
              key += '.';
            } else if (key in obj) {
              obj = obj[key];
              key = "";
            } else {
              return undefined;
            }
            break;

This case will use for some users .

**Comment by ansman** [comment]
This is intentional, please refer to the documentation: http://validatejs.org/#validate-nested

You can fix it by changing your constraints to this:
```
var constraints = {
  "basic\\.commandName": ...,
  "basic\\.name: ...,
  workingDirectory: ...
};
```

**Comment by vinothwindows47** [comment]
Thank you ansman

**Comment by ansman** [comment]
No problem, let me know if you find any issues with this.
