### ISSUE TITLE
Error message and automatically prepended attribute name

### ISSUE THREAD

**Issue by pjdevries** [ansman/validate.js#41]
Thank you very much for this useful library. I'm currently working on my first JavaScript/React project, and the language and framework independence of validate.js is important. 

Because of that pursuit for independence, I'm somewhat surprised that attribute names get prepended to error messages automatically. It seems to make assumptions about the way error messages are handled by the application. For instance, if I want to show the error message directly under the offending input field, having the attribute name as part of the message is kind of redundant. Is there a way around this?

**Comment by ansman** [comment]
I'm glad you find the library useful :)

Here something that might help you:
```javascript
var constraints = {
  username: {
    presence: true
  }
};

var errors = validate({}, constraints, {fullMessages: false});
console.log(errors);
// {username: ["can't be blank"]}

// Makes all the errors for the "username" field capitalized
console.log(errors.username.map(validate.capitalize));
// ["Can't be blank"];

// You can also use the ^ operator on custom messages
console.log(validate({}, {username: {presence: {message: "^Is required"}}}));
// {username: ["Is required"]}
```

**Comment by pjdevries** [comment]
Thanx for the swift reply. And yes, it did help. It also shows I must read all available documentation more carefully. This is the second time in one day that I asked a question on github to which the answer could be found in the docs. I sincerely apologize.

**Comment by ansman** [comment]
That's no problem at all, I'm happy to help :)

Let me know if there are any other issues.
