### ISSUE TITLE
Bower Install Not Finding Git Repository

### ISSUE THREAD

**Issue by venkatsep14** [ansman/validate.js#44]
bower validate.js#*         not-cached git://github.com/jaridmargolin/validate.js.git#*
bower validate.js#*            resolve git://github.com/jaridmargolin/validate.js.git#*
bower validate.js#*            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jaridmargolin/va
lidate.js.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by ansman** [comment]
Sorry about that, it's called just `validate` on bower (validate.js) was already taken.

Please try this command:
```
$ bower install validate
```

I've fixed the documentation as well.
