### ISSUE TITLE
Single length validation with "null" value its not working correctly

### ISSUE THREAD

**Issue by sandro-csimas** [ansman/validate.js#45]
````
validate.single(null, {length: {minimum: 3}})
// undefined
````
This function returns undefined. The correct should not be a validation error?

**Comment by sandro-csimas** [comment]
The same for an empty string:
````
validate.single('', {length: {minimum: 3}})
````
An empty string length is less than 3

**Comment by ansman** [comment]
Working as intended:
> 
Important! One thing that is a bit unorthodox is that most validators will consider empty values (null, undefined, whitespace only strings etc) valid values. So for example adding a constraint of at least 6 characters will be like saying If the attribute is given it must be at least 6 characters.

You need to use the `presence` validators as well.
