### ISSUE TITLE
Nested object magic interferes with dotted notation

### ISSUE THREAD

**Issue by gaggle** [ansman/validate.js#46]
Hi,

I think "dotted notation" (i.e. `{"foo.bar": true}` suffers from the magic surrounding nested objects.

```
  var constraints = {
    "foo\\.bar": {presence: true}
  };
  validate({"foo.bar": null}, constraints)
> "foo\\.bar": ["Foo bar can't be blank"]
```

Note the awkward backslashing, and the incorrect validation-error `Foo bar can't be blank` which should be `foo.bar can't be blank`

I've made a PR @ https://github.com/ansman/validate.js/pull/47 that shows how dotted notation must currently be used.

Does this feature behave like you want it to? Or have I missed something that makes this much simpler? It would be nice to have a way to differentiate between nested objects and dotted notation, but I haven't made sense of the code itself yet to make the change myself so I wanted to ask here.

**Comment by ansman** [comment]
Sorry I haven't gotten around to answering you sooner, I've wanted to give this some though and also I've been pretty busy.

I agree that the nested validation is not optimal as it is right now. The syntax stems from the fact that I assumed that nested validation would be more common than having attributes containing periods.
It's a hard problem and I still haven't found a solution to nested validation that I'm happy with, but I would gladly accept suggestions.

Regarding the validation message it's behaving as expected, `foo.bar` sounds very "techie" and I opted for having `Foo bar` instead. Though my intention was that people will probably have to customize the message anyway since for example `Address street can't be blank` is a pretty weird message with or without periods.

One solution to avoid having backslashes in the error messages would be to do something like this:
```javascript
var constraints = {
  "foo\\.bar": {presence: true}
};
validate({"foo.bar": null}, constraints)
// {"foo": {"bar": ["Foo bar can't be blank"]}}
```
What I don't like about that is that you need to type check the messages before printing them.

**Comment by gaggle** [comment]
No time pressure in this, just wanted to highlight what I found awkward. I'll look into customizing the messages, thanks.

For what its worth, in my use case the validation output is seen by other developers so "techie" feedback would be preferable. I think I'm looking for something like a `{resolvedots: false}` option that disables the dot-resolving (for both input-parsing and validation-messages) but I haven't given it a ton of thought yet.

Anyway, thanks for the reply.

**Comment by Jokero** [comment]
May be we can use nested objects to nested validation? 
Instead of:
```javascript```
validate(
    {
        from: {}
    },
    {
        'from.address.coordinates.latitude': {
            presence:     true,
            numericality: {
                greaterThanOrEqualTo: -90,
                lessThanOrEqualTo:    90,
                noStrings:            true,
                message:              'invalidValue'
            }
        },

        'from.address.coordinates.longitude': {
            presence:     true,
            numericality: {
                greaterThanOrEqualTo: -180,
                lessThanOrEqualTo:    180,
                noStrings:            true,
                message:              'invalidValue'
            }
        }
    }
);
```
use:
```javascript```
validate(
    {
        from: {}
    },
    {
        from: {
            address: {
                coordinates: {
                    latitude: {
                        $presence:     true,
                        $numericality: {
                            greaterThanOrEqualTo: -90,
                            lessThanOrEqualTo:    90,
                            noStrings:            true,
                            message:              'invalidValue'
                        }
                    },
                    longitude: {
                        $presence:     true,
                        $numericality: {
                            greaterThanOrEqualTo: -180,
                            lessThanOrEqualTo:    180,
                            noStrings:            true,
                            message:              'invalidValue'
                        }
                    }
                }
            }
        }
    }    
);
```
So for validators we use prefixed by `$` (or other symbol) name.

And for fields with `.` in name we don't use `\`:
```javascript```
validate(
    {
        'from.address.coordinates.latitude':  90,
        'from.address.coordinates.longitude': 90
    },
    {
        'from.address.coordinates.latitude': {
            $presence:     true,
            $numericality: {
                greaterThanOrEqualTo: -90,
                lessThanOrEqualTo:    90,
                noStrings:            true,
                message:              'invalidValue'
            }
        },

        'from.address.coordinates.longitude': {
            $presence:     true,
            $numericality: {
                greaterThanOrEqualTo: -180,
                lessThanOrEqualTo:    180,
                noStrings:            true,
                message:              'invalidValue'
            }
        }
    }
);
```

Nested format is more readable for multiple fields and deep nesting.
And I can use same validation object multiple times:
```javascript```
var locationConstraints = {
    address: {
        coordinates: {
            latitude: {
                $presence:     true,
                $numericality: {
                    greaterThanOrEqualTo: -90,
                    lessThanOrEqualTo:    90,
                    noStrings:            true,
                    message:              'invalidValue'
                }
            },
            longitude: {
                $presence:     true,
                $numericality: {
                    greaterThanOrEqualTo: -180,
                    lessThanOrEqualTo:    180,
                    noStrings:            true,
                    message:              'invalidValue'
                }
            }
        }
    }
};

validate(
    {
        from: {},
        to:   {}
    },
    {
        from: locationConstraints,
        to:   locationConstraints
    }
);
```

What do you think?

**Comment by gaggle** [comment]
:+1:

**Comment by ansman** [comment]
I considered nesting back when I developed this feature but opted for another approach since it would be tricky to differentiate between validator names and attributes names without a pretty major change in the syntax and thus breaking backwards compatibility.

But perhaps it is cleaner than the alternative, I'll have to think about it.

**Comment by tamtakoe** [comment]
Jokero format more flexible :+1: Current format is comfortable only for one level of nesting. Maybe leave it as an alternative

**Comment by ansman** [comment]
It looks nicer I agree but it has several drawbacks as well.

Representing the errors will be a lot trickier. What if the `address` attribute both has nested attributes as well as its own validation.
This would make the errors object both harder to read and understand. But I'm open suggestions of course, it's just that making such a major change in the syntax should come from a very clear reason.

**Comment by Jokero** [comment]
The reason is that the module is poorly suited for complex objects validation now :smiley: 

I think we may only allow the `presence` validator for fields like `address`

Example of complex constraints object:
```javascript
var locationConstraints = {
    startTime: {
        $presence: true,
        $datetime: true
    },

    endTime: {
        $presence: true,
        $datetime: true
    },

    address: {
        cityId: {
            $presence: true
        },

        terminalId: {
            $presence: function(value, attributes, attributeName, attributePath) {
                // attributePath is array ['from', 'address', 'terminalId']
                // or string 'from.address.terminalId'
                var from = attributes[attributePath[0]];
                return from.isTerminal;
            }
        },

        value: {
            $presence: function(value, attributes, attributeName, attributePath) {
                var from = attributes[attributePath[0]];
                return !from.isTerminal;
            }
        }
    },

    geo: {
        $presence: function(value, attributes) {
            var from = attributes[attributePath[0]];
            return !from.isTerminal;
        },

        latitude: {
            $presence:     true,
            $numericality: {
                greaterThanOrEqualTo: -90,
                lessThanOrEqualTo:    90
            }
        },

        longitude: {
            $presence:     true,
            $numericality: {
                greaterThanOrEqualTo: -180,
                lessThanOrEqualTo:    180
            }
        }
    }
};

var needValidate = {
    from: locationConstraints,
    to:   locationConstraints
};
```

`geo` has presence validator and properties with validators. If it's not specified validate.js returns error message (can't be blank) and does not run validators of own properties (latitude and longitude).

Or we can use syntax similar to [JSON Schema](http://json-schema.org/example1.html) (use `properties` and some other cool stuff):
```javascript
var locationConstraints = {
    startTime: {
        presence: true,
        datetime: true
    },

    endTime: {
        presence: true,
        datetime: true
    },

    address: {
        properties: {
            cityId: {
                presence: true
            },

            terminalId: {
                presence: function(value, attributes, attributeName, attributePath) {
                    // attributePath is array ['from', 'address', 'terminalId']
                    // or string 'from.address.terminalId'
                    var from = attributes[attributePath[0]];
                    return from.isTerminal;
                }
            },

            value: {
                presence: function(value, attributes, attributeName, attributePath) {
                    var from = attributes[attributePath[0]];
                    return !from.isTerminal;
                }
            }
        }
    },

    geo: {
        presence: function(value, attributes) {
            var from = attributes[attributePath[0]];
            return !from.isTerminal;
        },

        properties: {
            latitude: {
                presence:     true,
                numericality: {
                    greaterThanOrEqualTo: -90,
                    lessThanOrEqualTo:    90
                }
            },

            longitude: {
                presence:     true,
                numericality: {
                    greaterThanOrEqualTo: -180,
                    lessThanOrEqualTo:    180
                }
            }
        }
    }
};
```

**Comment by ansman** [comment]
@Jokero I totally get the reasoning but as I mentioned, how should the resulting errors object look?

**Comment by Jokero** [comment]
@ansman Sorry for delay :) 

Example config:
```javacript
{
    a: {
        type: 'object', // validator

        properties: {
            b: {
                type: 'string',
                required: true
            }
        }
    }
}
```

Examples:

1)
```javacript
var a = 123;
```

Error:
```javacript
{
    a: ['notObject']
}
```

2)
```javacript
var a = {};
```

Error:
```javacript
{
    a: {
        b: ['required']
    }
}
```

3)
```javacript
var a = { b: 123 };
```

Error:
```javacript
{
    a: {
        b: ['notString']
    }
}
```

**Comment by ansman** [comment]
This syntax was exactly what I wanted to avoid when writing this library, I wanted to avoid having types in the library. The beauty of the current implementation is how easy it is to customize, extend and understand.

If that syntax is what you're looking for I don't think validate.js is the library you want to use.

**Comment by ayeressian** [comment]
@ansman have you consider to use jsonpath to better support nested properties? http://goessner.net/articles/JsonPath/

**Comment by ansman** [comment]
No, but that looks promising.

**Comment by vixriihi** [comment]
Here is little revised suggestion to tackle the nested issue and the error messages

``` json
{
  "a": {
    "customValidator": {
      "message": "custom error message"
    },
    "properties": {
      "b": {
        "presence": true,
        "length": {
          "minimum": 6,
          "message": "must be at least 6 characters"
        }
      },
      "c": {
        "presence": true,
        "length": {
          "minimum": 2,
          "message": "at least 2 cs must be given"
        },
        "items": {
          "e": {
            "presence": true
          }
        }
      }
    }
  }
}
```
I also made the validators into an array so that they can be ordered and that the
validation chain can be stopped if wanted. Values validator could be pr #119


Success data:
```js

var data = {
    a:{
        custom: "to succeed",
        b: "123456",
        c: [
          {
            e: "foo"
          },
          {
            e: "bar"
          }
        ]
    }
}
```

Error case:
```js

var data = { a: { c : [ {} ] } }
```

Error object:

``` json
{
  "a:errors": ["custom error message"],
  "a": {
    "b:errors": ["required"],
    "c:errors": ["atleast 2 cs must be given"],
    "c": [
      {
        "e:errors":["required"]
      }
    ]
  }
}
```
Alternative form for the errors:
``` json
{
  "a": ["custom error message"],
  "a.b": ["required"],
  "a.c": ["atleast 2 cs must be given"],
  "a.c[0].e": ["required"]
}
```

**Comment by loopmode** [comment]
@vixriihi What is it with "items" and "properties" in your last example? Is this wishful pseudo-code inspired by JSONSchema, or does validate.js actually support it and it's just not documented?
(I am struggling with array item validation lately, totally missing such a feature...)

**Comment by vixriihi** [comment]
It's just wishful pseudo-code inspired by JSONSchema. So unfortunately at least not yet supported by validate.js

**Comment by Jokero** [comment]
@gaggle @ansman I published `validy` module (https://github.com/Jokero/validy) which supports nested object validation, asynchronous and custom validators. So you can try to use it
