### ISSUE TITLE
Numbers length validation

### ISSUE THREAD

**Issue by tomyf** [ansman/validate.js#49]
Hello there !
Thanks for this library, I find it very useful and very rich in its features :+1: 
I was wondering if there was any way of validation a number's length.

I'm using a workaround as follows : 
```
numericality : {
  onlyInteger : true,
  greaterThan : 9999
}
```

It would be more convenient to be able to write something similar to strings : 
```
numericality : {
  onlyInteger : true
},
length : {
  minimum : 5
}
```

Thank you for your time,
Thomas

**Comment by ansman** [comment]
Well, semantically numbers have no length so I'm not that keen on adding support for it. However, you can customize the message be whatever you want. 

What exactly are you validating? Postal codes?

**Comment by tomyf** [comment]
I am validating number for business purposes that should be between, let's say 5 and 10 digits, so it is a Number and I should write : 
```
numericality : {
  onlyInteger : true,
  greaterThanOrEqualTo : 10000,
  lowerThan : 10000000000
}
```
The 'lowerThan' value is not really convenient :)

Maybe I could, instead, write a custom validator that would parse the number to a String and apply a regexp on it ?

**Comment by ansman** [comment]
You could easily make the length validator do what you want:
```
var length = validate.validators.length;
validate.validators.length = function(value, options, key, attributes) {
    if (validate.isNumber(value)) {
      value = "" + value;
    }
    return length.call(this, value, options, key, attributes);
}

validate({foo: 4000}, {foo: {length: {minimum: 5}}});
// => {foo: ["Foo is too short (minimum is 5 characters)"]}
```

**Comment by tomyf** [comment]
Indeed, thank you !
Also, thank you very much for your time, and sorry I took so long time to reply :)
