### ISSUE TITLE
Make easy to integrate with angular input[date]

### ISSUE THREAD

**Issue by jacargentina** [ansman/validate.js#56]
I'm using angular, which when using input[date] forces the ng-model to be a Date() object.
AFAIK, validatejs expects the target object to be a "string date".

Wouldn't be nice to make validatejs a little intelligent to detect that the validated property has a Date in it, and pass it to momentjs ?

Or maybe there is something i'm missing and the solution is already there?

**Comment by ansman** [comment]
Validate.js works with native dates already:
```javascript
var constraints = {createdAt: {datetime: true}};
validate({createdAt: "foo"}, constraints);
// => {"createdAt": ["Created at must be a valid date"]}
validate({createdAt: new Date(), constraints);
// => undefined
```

I've added some tests for this in 1fb4f3f
