### ISSUE TITLE
Custom validation messages are not that custom.

### ISSUE THREAD

**Issue by dherault** [ansman/validate.js#68]
Hi, nice object validation librairy, its size and flexibility makes it perfect for isomorphic apps!

But I feel like something can be improved with the validation messages, with the current API you have:
```javascript
validate({}, {username: {presence: true}})
// => {"username": ["Username can't be blank"]}

validate({}, {username: {presence: {message: "is required"}}})
// => {"username": ["Username is required"]}
```

While I *believe* most people would like:
```javascript
validate({}, {username: {presence: true}})
// => {"username": ["Username can't be blank"]}

validate({}, {username: {presence: {message: "Some really custom message"}}})
// => {"username": ["Some really custom message"]}
```
See what I mean, just drop the key prefix!
It would facilitate internationalization and allow unreadable keys to be validated discretely:
```javascript
// current API
validate({}, {username: {presence: {message: "是必须的"}}})
// => {"username": ["Username 是必须的"]}

validate({}, {w31rdK3y: {presence: {message: "is required"}}})
// => {"w31rdK3y": ["W31rdK3y is required"]}

// expected API
validate({}, {username: {presence: {message: "用户名是必需的"}}})
// => {"username": ["用户名是必需的"]}

validate({}, {w31rdK3y: {presence: {message: "Username is required"}}})
// => {"w31rdK3y": ["Username is required"]}
```

Problem is, it's a breaking change... But I'm ready to submit a PR if you want me to.
Tell me what you think, hope this makes sense.

**Comment by dherault** [comment]
Just read the source code, and saw the '^' thingy, my bad -_-

**Comment by ansman** [comment]
@dherault The library wasn't designed with i18n in mind which is why it's a bit clunky, but you can change the default messages however.

My original plan was to switch to use a printf type formatting for keys etc but it's tricky since validate.js can't capitalize properly unless it knows exactly where it adds the key.

There is the `fullMessages` option which disables attribute name prefixing for all validators.

**Comment by dherault** [comment]
Thanks, I'll take a look at it!

**Comment by yannderycke** [comment]
Just put ^ before your text message like: 
var constraints = {
  birthday: {
    datetime: {
      dateOnly: true,
      latest: moment.utc().subtract(18, 'years'),
      message: "^You need to be at least 18 years old"
    }
  }
};
