### ISSUE TITLE
Problem with Whitespace character  (/s)

### ISSUE THREAD

**Issue by JordiMontesSanabria** [ansman/validate.js#70]
I'm using validate.js for validate a form in a payment page. It is working fine but i have a trouble with whitespaces. For validae cardholder's name I use

```javascript
creditName: {
                presence: {message: "^El nombre es obligatorio."},
                format: {
                    pattern: "[a-záéíóúàèìòùñäëüö\s]+",
                    //flags: "i",
                    message: "^Solo puede contener letras."
                }
            }
```

This should works fine but I get a filed test when I put things like "Jordi Montes Sanabria" or "J M s". However all goes good when i put for exemple "jordiMontesSanabria".

Anyone know if its my error or i am doing somthing wrong? It's a library limitation?

Thanks for all.

**Comment by ansman** [comment]
I believe you need to double escape the s (`\\s`) since it's in a string.

**Comment by ansman** [comment]
Yup, this works:
```javascript
validate.single("Foo bar", {format: {pattern: "[a-z\\s]+", flags: "i"}})
=> undefined
```

**Comment by JordiMontesSanabria** [comment]
Yes, it works. I belive that it was with /.../ form.


Thanks.
