### ISSUE TITLE
Allow default values and formatted values

### ISSUE THREAD

**Issue by fnky** [ansman/validate.js#75]
### Default Values
If a validation is falsy and `default` option is set, it will simply return a default value instead of an error for given attribute.

The `default` option accepts all types, including `Function` which returns a value of any type.

```js
var constraints = {
  lang: {
    within: ['en', 'da', 'fr'],
    default: 'en'
  },
  about: {
    presence: true,
    default: function (value, options, key, attributes) { return 'N/A' }
  }
}

validate({ lang: 'no' }, constraints)
// => { lang: 'en', about: 'N/A' }
```

### Formatted Values
If a validation is truthy and `format` option is set, it will return a formatted value

The `format` options accepts a `Function` which returns a value of any type.

```js
var constraints = {
  username: {
    url: true,
    format: function (value, options, key, attributes) { return value + '_key'.toLowerCase() }
  }
}
```

### Function
The function accepted by both _transforms_ accepts the same arguments as regular validation options.

`function (value, options, key, attributes)`

### Discussion
The above proposal is fairly easy, however this could potentially cause conflicts. I propose a new addition to the API called **transforms**. As above both `format` and `default` are transforms, that accepts given value to _transform_ and returns a value.

An example of API could be, though needs a way to choose which options to respect (e.g. `presence`)

```js
validate.transforms.format = (value, fn, key, attributes) {
  return fn(value, key, attributes)
}
```

**Comment by ansman** [comment]
This wouldn't be in the scope of this library, it could be done without any dependencies of validate.js
