### ISSUE TITLE
Add type validator

### ISSUE THREAD

**Issue by Jokero** [ansman/validate.js#80]
Basic types:
- object (plain object)
- array
- integer
- number
- string
- boolean
- null

Example:

``` javascript
validate.single([1, 2, 3], { type: 'array' }); // undefined
validate.single('123', { type: 'array' }); // ['is not an array']
```

User should be able to add own or modify existing types:

``` javascript
validate.validators.type.options = { notIntegerArray: 'is not an array of integers' };

// validate.validators.type.checks contains all types validation rules
validate.validators.type.checks.integerArray = function(value) {
    if (!Array.isArray(value)) {
        return false;
    }

    for (var i in value) {
        if (!Number.isInteger(value[i])) {
            return false;
        }
    }

    return true;
};

// ...

validate.single([1, 2, 3], { type: 'integerArray' }); // undefined
validate.single(['1', '2', '3'], { type: 'integerArray' }); // ['is not an array of integers']
```

**Comment by ansman** [comment]
I'm guessing this would be a mostly server side validator since the end user cannot really do anything to fix the error if it's used in a browser.

The number/integer version already exists with the `numericality` validator.
And what would the purpose of the `null` check be?

I'm weighing between this being a separate validators or one that does it all.

**Comment by fnky** [comment]
+1 This would be helpful both client- and server-side. Also could allow for custom type comparators for custom types, or perhaps use actual objects/prototypes for comparison:

```js
var constraints = {
  name: { type: String },
  age: { type: Number },
  multiple: { type: [String, Boolean, Number] },
  custom: { type: User }
}

var data = {
  age: 17,
  name: 'John',
  multiple: true, // can also be String and Number
  custom: new User()
}

v(data, constraints)
``` 

I had made a partial working validator for this already, but not a comprehensive one.

**Comment by Jokero** [comment]
@ansman Yes, it's mostly for the backend. I think it should be one validator. We can use `numericality` only to compare numbers.
`null` can be useful when we want to remove any object in PATCH request for example (how does github https://developer.github.com/v3/gists/#edit-a-gist)

**Comment by Screeze** [comment]
I also was looking for this, so I added it as custom validator. Might be useful for somebody else, or maybe somebody wants to integrate it into the library?

```javascript
validate.validators.type = function(value, options, key, attributes) {
   // allow empty values by default (needs to be checked by "presence" check)
   if(value === null || typeof value === 'undefined') {
      return null;
   }

   // allow defining object of any type using their constructor. --> options = {clazz: ClassName}
   if(typeof options  === 'object' && options.clazz) {
      return value instanceof options.clazz ? null : ' is not of type "' + options.clazz.name + '"';
   }

   if(!validate.validators.type.checks[options]) {
      throw new Error("Could not find validator for type " + options);
   }
   return validate.validators.type.checks[options](value) ? null : ' is not of type "' + options + '"' ;
};
validate.validators.type.checks = {
   Object: function(value) {
      return validate.isObject(value) && !validate.isArray(value);
   },
   Array: validate.isArray,
   Integer: validate.isInteger,
   Number: validate.isNumber,
   String: validate.isString,
   Date: validate.isDate,
   Boolean: function(value) {
      return typeof value === 'boolean';
   }
};
```

It also supports something like this:
```javascript
{
    test: {
        type: {clazz: TestClass}
    },
}
```
(Sadly options cannot be the object itself like `type: TestClass`, because if options is a Function, it gets evaluated by validate.js to allow dynamic options based on the value. Thats why I used this object with clazz property)

**Comment by jordanh** [comment]
+1 to this (and thank you @Screeze). I'm using `validator` to validate function parameters. Type checking is very useful.

**Comment by Shulin** [comment]
I'd like to give my vote for this.

I'm really surprised there wasn't type checking to begin with.

Thank you @Screeze  for the validator. I'll be using that for now.

**Comment by nicodewet** [comment]
+1, handy for server-side validation. Going to roll with the @Screeze option in the meantime.

**Comment by magic-madrigal** [comment]
+1

**Comment by ansman** [comment]
This has been implemented and will be released in the next version.

**Comment by emckay** [comment]
Awesome! When will the next version be published? Anything blocking the next release that a new contributor could help with?

**Comment by hhff** [comment]
Hi - echo'ing @emckay - anything we can do to get this out?

**Comment by AndreasGassmann** [comment]
I just tested the master branch and it seems to work. Anything that still needs to be done to get it into the next release?
