### ISSUE TITLE
How to validate arrays and also make sure all array elements match specific criteria?

### ISSUE THREAD

**Issue by rightaway** [ansman/validate.js#85]
Is there a way to validate arrays, to say something like the array must have between 3 and 5 elements? And then to validate within the array, to make sure that each of those 3 to 5 elements are email addresses, or numbers greater than 100?

**Comment by ansman** [comment]
You can use the `length` validator for validating the number of items but you currently cannot validate the objects in the array with a single validation call, instead you'd have to validate each array object manually.

There is a ticket for better array support (#1) so I'm closing this for now.
