### ISSUE TITLE
Extend email validator to supporting punycode format.

### ISSUE THREAD

**Issue by grushikhin** [ansman/validate.js#87]
Hi!
We use your's validator for validate email addresses.

Now, we have a problem.
We use native input[type="email"].
When user inputs email like "моя@россия.рф", the value of the input field is "моя@xn--h1alffa9f.xn--p1ai".
Your regexp dissalow digits and hyphens in last part of email address (xn--p1ai) and this email marked as invalid.
Could You fix your regexp for this case?

**Comment by ansman** [comment]
Sorry but you'll have to either tweak the regex by setting `validate.validators.email.PATTERN` or by converting from punycode before validating.

Punycode is an encoding and supporting it would be like supporting base64, it is not a valid email and will be treated as such.
