### ISSUE TITLE
How to validate booleans?

### ISSUE THREAD

**Issue by tobiasmuecksch** [ansman/validate.js#89]
I'd like to validate an object of booleans. I want to prevent my users from sending custom requests to the server containing any other type than booleans.

I haven't found a suitable validator. Does validate.js lack of that capability or is there a way to achieve this?

**Comment by tobiasmuecksch** [comment]
I already found out: http://validatejs.org/#custom-validator

Sorry so much for posting nonsense!

**Comment by ansman** [comment]
This is definitely not nonsense :)
A ticket has been opened (#66 based on #65) to support this.

Until that has been fixed you can use the `inclusion` validator:
```
var constraints = {
  checkbox: {
    presence: {
      message: "^You need to check the checkbox"
    },
    inclusion: {
      within: [true],
      message: "^You need to check the checkbox"
    }
  }
};

validate({checkbox: false}, constraints)
// => {"checkbox": ["You need to check the checkbox"]}

validate({checkbox: true}, constraints)
// => undefined
```

**Comment by tobiasmuecksch** [comment]
@ansman Thanks :)
