### ISSUE TITLE
Bump the version number for NPM, etc

### ISSUE THREAD

**Issue by splicebison** [ansman/validate.js#90]
Latest changes for dates (notValid, tooEarly, tooLate) in options can not be updated via NPM.

**Comment by ansman** [comment]
0.10.0 isn't ready yet but you can install a specific commit by using this command:
`npm install --save "ansman/validate.js#a037742a9e5ffa945df3e2b20e03e9a8fb9f0a0d"`

Or by adding this to your `package.json`:
```json
{
  "dependencies": {
    "validate.js": "ansman/validate.js#a037742a9e5ffa945df3e2b20e03e9a8fb9f0a0d"
  }
}
```
