### ISSUE TITLE
new bower version (0.9.1)

### ISSUE THREAD

**Issue by jfreyre** [ansman/validate.js#92]
Hi,

Could you register a new tag (0.9.1) that will allow us to register a new version on bower and benefits last commits ?

**Comment by ansman** [comment]
0.10.0 isn't ready yet but you can install a specific commit by using this command:
`bower install --save "validate.js#a037742a9e5ffa945df3e2b20e03e9a8fb9f0a0d"`

Or by adding this to your `bower.json`:
```json
{
  "dependencies": {
    "validate.js": "a037742a9e5ffa945df3e2b20e03e9a8fb9f0a0d"
  }
}
```
