### ISSUE TITLE
moment.js 2.9.0 has known vulnerabilities

### ISSUE THREAD

**Issue by leighfarrell** [ansman/validate.js#96]
Seeing warnings when running `grunt-retire` on a project that uses `validate.js`:
```
Running "retire:js" (retire) task
Loading from cache: https://raw.github.com/RetireJS/retire.js/master/repository/jsrepository.json
>> public/components/validate/specs/vendor/moment.js
>> ↳ moment.js 2.9.0 has known vulnerabilities: severity: low; summary: reDOS - regular expression denial of service; https://github.com/moment/moment/issues/2936
Warning: Task "retire:js" failed. Use --force to continue.

Aborted due to warnings.
```

Will need to update version of `moment.js`.

Added bonus: add `grunt-retire` to `grunt test` and `grunt build` tasks to check for warnings/deprecations.

**Comment by ansman** [comment]
Validate.js only uses moment.js for testing and has no dependencies on it. But will update anyway.

**Comment by ansman** [comment]
Also, this project is currently using 2.10.6 and not 2.9.0 so it would seem that retire.js is incorrect in this case.

**Comment by leighfarrell** [comment]
Cheers!
