### ISSUE TITLE
Handle date split over multiple fields?

### ISSUE THREAD

**Issue by glenjamin** [ansman/validate.js#97]
We're building a form with date represented as 3 fields:
```
[DD] [MM] [YYYY]
```

I'd like to use the `datetime` validator to handle this, but I'm not sure how to make it work.

The alternative I've come up with looks like this:

```js
validate.validators.dob = function(value, options, key, attributes) {
	var year = attributes[options.year] || '1fail1';
	var month = attributes[options.month] || '1fail1';
	var day = attributes[options.day] || '1fail1';

	var date = new Date([year, month, day].join('-'));

	return isNaN(date) ? '^invalid' : null;
};
```

I'm wondering if it would be possible / worthwhile to include something like this in the core lib?

**Comment by ansman** [comment]
You can easily proxy the call to the validator yourself by just calling `validate.validators.date(...)`.

**Comment by glenjamin** [comment]
Ah, that's a good idea - my custom validator would just handle the conversion of multiple fields into one, and then pass things on?

**Comment by ansman** [comment]
Exactly. The options could be proxied as well.

**Comment by glenjamin** [comment]
Nice one, thanks!

This lib is great by the way - constraints on data is exactly how I like to think about validations!

**Comment by ansman** [comment]
I'm glad you like it!
